# App Identity
spring.application.name=course-management-app

# Server Config
server.port=9069

# H2 In-Memory Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console  # optional, good to explicitly set

# JPA (Hibernate)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf View Settings
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

debug=true
